<?php
declare(strict_types=1);
/**
 * Print-optimized report view. Opens with auto-print so the user can
 * "Save As PDF" from any browser. Drop-in replacement target if you
 * later swap in TCPDF or DomPDF.
 */
?><!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Report &mdash; <?= htmlspecialchars($systemName) ?> &mdash; <?= htmlspecialchars($rangeLabel) ?></title>
<style>
  @page { size: A4; margin: 14mm 12mm; }
  *{box-sizing:border-box}
  body{font-family: 'Helvetica Neue', Arial, sans-serif; color:#0f172a; margin:0; padding:18px;}
  h1,h2,h3{margin:0;color:#005f8f}
  h1{font-size:22px}
  h2{font-size:16px;margin-top:20px;border-bottom:1px solid #cbd5e1;padding-bottom:6px}
  h3{font-size:14px}
  .meta{color:#475569;font-size:12px;margin-top:4px}
  .header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid #f4b400;padding-bottom:10px;margin-bottom:14px}
  .header .right{text-align:right;font-size:12px;color:#475569}
  .kpi{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0 18px}
  .kpi .box{border:1px solid #e2e8f0;border-radius:8px;padding:10px 12px}
  .kpi .label{font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.04em}
  .kpi .value{font-size:18px;font-weight:800;color:#005f8f}
  table{width:100%;border-collapse:collapse;margin-top:6px;font-size:12px}
  th,td{padding:7px 8px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}
  th{background:#f1f5f9;color:#0b1f4d;font-size:11px;text-transform:uppercase;letter-spacing:.04em}
  .right-col{text-align:right}
  .footer{margin-top:24px;font-size:11px;color:#64748b;text-align:center}
  @media print {
    .no-print { display:none }
    body{padding:0}
  }
</style>
</head>
<body>
  <div class="no-print" style="text-align:right;margin-bottom:10px">
    <button onclick="window.print()" style="background:#005f8f;color:#fff;border:0;border-radius:6px;padding:8px 14px;font-weight:700;cursor:pointer">Print / Save as PDF</button>
  </div>

  <div class="header">
    <div>
      <h1><?= htmlspecialchars($systemName) ?></h1>
      <div class="meta">Performance Report</div>
    </div>
    <div class="right">
      <div><strong>Range:</strong> <?= htmlspecialchars($rangeLabel) ?></div>
      <div><strong>Generated:</strong> <?= htmlspecialchars($generatedAt) ?></div>
    </div>
  </div>

  <h2>Summary</h2>
  <div class="kpi">
    <div class="box"><div class="label">5★ Reviews Redirected</div><div class="value"><?= (int)$stats['total_5star_redirected'] ?></div></div>
    <div class="box"><div class="label">Internal Feedback (1-3★)</div><div class="value"><?= (int)$stats['total_internal_feedback'] ?></div></div>
    <div class="box"><div class="label">New Businesses</div><div class="value"><?= (int)$stats['new_businesses'] ?></div></div>
    <div class="box"><div class="label">Active Businesses</div><div class="value"><?= (int)$stats['active_businesses'] ?></div></div>
    <div class="box"><div class="label">Wallet Credited</div><div class="value">&#8377;<?= (int)$stats['total_credited'] ?></div></div>
    <div class="box"><div class="label">Wallet Debited</div><div class="value">&#8377;<?= (int)$stats['total_debited'] ?></div></div>
  </div>

  <h2>Per-Business Performance</h2>
  <?php if (empty($perBusiness)): ?>
    <p class="meta">No data in selected range.</p>
  <?php else: ?>
    <table>
      <thead><tr><th>#</th><th>Business</th><th>Category</th><th>Mobile</th><th class="right-col">5★</th><th class="right-col">Internal</th><th class="right-col">Wallet</th></tr></thead>
      <tbody>
        <?php $i = 1; foreach ($perBusiness as $row): ?>
          <tr>
            <td><?= $i++ ?></td>
            <td><strong><?= htmlspecialchars($row['business_name']) ?></strong><br><span class="meta"><?= htmlspecialchars($row['email']) ?></span></td>
            <td><?= htmlspecialchars($row['category_name']) ?></td>
            <td><?= htmlspecialchars((string)$row['mobile']) ?></td>
            <td class="right-col"><?= (int)$row['total_5star'] ?></td>
            <td class="right-col"><?= (int)$row['total_internal'] ?></td>
            <td class="right-col">&#8377;<?= (int)$row['wallet_balance'] ?></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>

  <?php if (!empty($dailyBreakdown)): ?>
    <h2>Daily Breakdown (5★ Redirects)</h2>
    <table>
      <thead><tr><th>Date</th><th class="right-col">Reviews</th></tr></thead>
      <tbody>
        <?php foreach ($dailyBreakdown as $d): ?>
          <tr><td><?= htmlspecialchars((string)$d['d']) ?></td><td class="right-col"><?= (int)$d['reviews'] ?></td></tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  <?php endif; ?>

  <div class="footer">
    Generated by <?= htmlspecialchars($systemName) ?> &middot; This report contains data from <?= htmlspecialchars($rangeLabel) ?>.
  </div>

  <script>
    window.addEventListener('load', function(){ setTimeout(function(){ window.print(); }, 300); });
  </script>
</body>
</html>
